---
dotfiles_dir: "{{ playbook_dir }}/dotfiles"
# dotfiles_secrets_src:
dotfiles_secrets_dest: "{{ ansible_env.HOME }}"
dotfiles_use_links: true

dotfiles_links_vscode_settings_dir: "{{ lookup('env', 'HOME') }}/Library/Application Support/Code/User"
dotfiles_auth_home: "{{ lookup('env', 'HOME') }}/.secrets"

# XDG Base Directory Specification (https://specifications.freedesktop.org/basedir/latest/)
XDG_BASE_DIRS: # noqa var-naming[pattern]
  XDG_CONFIG_HOME: "{{ lookup('env', 'XDG_CONFIG_HOME') | default(ansible_facts['env']['HOME'] + '/.config', true) }}" # noqa var-naming[pattern]
  XDG_CACHE_HOME: "{{ lookup('env', 'XDG_CACHE_HOME') | default(ansible_facts['env']['HOME'] + '/.local/cache', true) }}"
  XDG_DATA_HOME: "{{ lookup('env', 'XDG_DATA_HOME') | default(ansible_facts['env']['HOME'] + '/.local/share', true) }}"
  XDG_STATE_HOME: "{{ lookup('env', 'XDG_STATE_HOME') | default(ansible_facts['env']['HOME'] + '/.local/state', true) }}"
  XDG_RUNTIME_DIR: "{{ lookup('env', 'XDG_RUNTIME_DIR') | default(ansible_facts['env']['HOME'] + '/.local/run', true) }}"
  XDG_BIN_HOME: "{{ lookup('env', 'XDG_BIN_HOME') | default(ansible_facts['env']['HOME'] + '/.local/bin', true) }}"
