---
version: "1"
git_protocol: ssh
editor: nano
prompt: enabled
pager: cat
aliases:
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> de4d691 (Added gh aliases)
  prc: pr create -f
  prcd: pr create -f --draft
  prdy: pr ready
  v: pr view --web
<<<<<<< HEAD
=======
  co: pr checkout
  ghw: pr view --web
>>>>>>> c57576d (Merged dotfiles from afonsoc12/dotfiles)
=======
>>>>>>> de4d691 (Added gh aliases)
