---
# ==================================================
# Task: iterm
# ==================================================
ide_zsh_path: >-
  {{
    lookup('env', 'ZSH')
    | default(lookup('env', 'XDG_DATA_HOME') ~ '/oh-my-zsh', true)
    | default(lookup('env', 'HOME') ~ '/.local/share/oh-my-zsh', true)
  }}

# ==================================================
# Task: vscode
# ==================================================
ide_vscode_extensions: []
