---
- name: "Install Temurin version {{ item }}"
  homebrew_cask:
    name: "temurin@{{ item }}"
    state: present

- name: jEnv init # noqa: name[casing]
  shell: eval "$(jenv init -)"
  changed_when: false

- name: Get home path for Java {{ item }}
  shell: set -o pipefail && /usr/libexec/java_home -v {{ item }} | grep {{ item }}
  register: java_home
  changed_when: false
  failed_when: >-
    java_home.rc != 0
    or java_home.stdout == ""
    or java_home.stdout_lines | length != 1
    or ("-" ~ item ~ "." not in java_home.stdout and "/" ~ item ~ "." not in java_home.stdout)

- name: Add Java version {{ item }} to jEnv # noqa: name[template]
  command: jenv add {{ java_home.stdout }}
  register: java_jenv_add
  changed_when: "'added' in java_jenv_add.stdout"
  failed_when: "java_jenv_add.rc !=0 or 'is not a valid path to java installation' in java_jenv_add.stdout"

- name: Add Java version {{ item }} (major version alias) to jEnv # noqa: name[template]
  file:
    src: "/Library/Java/JavaVirtualMachines/temurin-{{ item }}.jdk/Contents/Home"
    dest: "~/.jenv/versions/{{ item }}"
    state: link
    mode: "0755"
