---
- name: Install iTerm (homebrew)
  homebrew_cask:
    name: iterm2
    state: present

- name: Check if oh-my-zsh is already installed
  stat:
    path: "{{ ide_zsh_path }}"
  register: ide_zsh_dir

- name: Create temporary file
  ansible.builtin.tempfile:
    state: file
    suffix: oh-my-zsh-install.sh
  register: ide_tempfile
  when: ide_zsh_dir.stat.exists is false

- name: Download oh-my-zsh installation script
  get_url:
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: "{{ ide_tempfile.path }}"
    mode: "0755"
  when: ide_zsh_dir.stat.exists is false

- name: Install oh-my-zsh
  command: bash {{ ide_tempfile.path }} --unattended --keep-zshrc
  environment:
    ZSH: "{{ ide_zsh_path }}"
  changed_when: true
  when: ide_zsh_dir.stat.exists is false

- name: Install Powerlevel10k theme
  homebrew:
    name: powerlevel10k
